version: "3.0"

services: 
  server:
    build: ./backend
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: mongo
    command: mongod --port 5000 --bind_ip_all
    ports:
      - 27017:5000
