version: "3.0"

services: 
  server:
    build: ./backend
    volumes: 
      - ./backend:/usr/app/
      - /usr/app/node_modules
    ports:
      - 3000:3000
    links:
      - database

  database:
    image: mongo
    ports:
      - 5000:5000
